development:
  adapter: postgresql
  encoding: unicode
  database: halfstack_development
  pool: 5
  username: Ben
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: halfstack_test
  pool: 5
  username: Ben
  password: